# [Numpy](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)

* Environment require **Python 3+**
* 3-Party module
---

In [4]:
import numpy as np

## Create a Simple Numpy Array

In [82]:
List_myHeight = [150, 160, 170]
Np_myHeight =np.array(List_myHeight)

print('Type of np.array = ', type(Np_myHeight))
print('Data type in Array = ', Np_myHeight.dtype)
print('Dimension of Array = ', Np_myHeight.ndim)

Type of np.array =  <class 'numpy.ndarray'>
Data type in Array =  int64
Dimension of Array =  1


* Numpy array could be caculated as below

In [21]:
Np_myWeight = np.array([50,54,80])
BMI = Np_myWeight/((Np_myHeight*0.01)**2)

print('BMI =', BMI)
print('BMI>24 =', BMI>24)

BMI = [ 22.22222222  21.09375     27.6816609 ]
BMI>24 = [False False  True]


## Create Simple Array
* with np.arrange()

## Stacking
* np.vstack([array1, array2])
* np.hstack([array1, array2])

In [112]:
a = np.arange(0, 100, 20)
b = np.arange(5)

print('a =', a)
print('b =', b)

a = [ 0 20 40 60 80]
b = [0 1 2 3 4]


In [105]:
np.vstack([a,b])

array([[ 0, 20, 40, 60, 80],
       [ 0,  1,  2,  3,  4]])

In [78]:
np.hstack([a,b])

array([ 0, 20, 40, 60, 80,  0,  1,  2,  3,  4])

## Multiple Dimensions Array

* 2 Dimensions

In [84]:
A = np.array( [[0,2],
               [1,3]] )

B = np.array( [[0,3], 
               [2,4]] )

In [142]:
print('★ Dimension of Array = ', A.ndim)
print('★ Shape of Array = ', A.shape)
print('★ Number of elements of the array = ', C.size)
print('★ Transpose A Array I=\n', A.T)
print('★ Transpose A Array II =\n', A.transpose())

★ Dimension of Array =  2
★ Shape of Array =  (2, 2)
★ Number of elements of the array =  18
★ Transpose A Array I=
 [[0 1]
 [2 3]]
★ Transpose A Array II =
 [[0 1]
 [2 3]]


* Caculate with Array

|A Array                     |B Array  |
|----------------------------|----------------------------|
|[[0,2],<br> [1,3]]</br>     |[[0,3],<br> [2,4]]</br>|


In [127]:
print('★ Aarry A Power 2 = \n', A**2)
print('★ Array A*B = \n', A*B)
print('★ Array A+B = \n', A+B)
print('★ Array A dot B = \n', A.dot(B))
print('★ Array A dot B = \n', np.dot(A,B))
print('★ Sum of Each Column =', A.sum(axis=0))
print('★ Sum of Each Row =', A.sum(axis=1))
print('★ Min of Each Row',A.min(axis=1))
print('★ Max of Each Row',A.max(axis=1))

★ Aarry A Power 2 = 
 [[0 4]
 [1 9]]
★ Array A*B = 
 [[ 0  6]
 [ 2 12]]
★ Array A+B = 
 [[0 5]
 [3 7]]
★ Array A dot B = 
 [[ 4  8]
 [ 6 15]]
★ Array A dot B = 
 [[ 4  8]
 [ 6 15]]
★ Sum of Each Column = [1 5]
★ Sum of Each Row = [2 4]
★ Min of Each Row [0 1]
★ Max of Each Row [2 3]


* 3 Dimensions

In [139]:
C = np.array( [[[0, 8, 10], 
                [2, 6, 20]],
               [[5, 7, 30], 
                [2, 9, 40]],
               [[5, 2, 50], 
                [4, 3, 60]]])

print('★ Dimension of Array = ', C.ndim)
print('★ Shape of Array C = ', C.shape)
print('★ Value at location (2,1,1) = ', C[2,1,2])
print('★ Cumulative Sum Along Each Column =\n', C.cumsum(axis=0))

★ Dimension of Array =  3
★ Shape of Array C =  (3, 2, 3)
★ Value at location (2,1,1) =  60
★ Cumulative Sum Along Each Column =
 [[[  0   8  10]
  [  2   6  20]]

 [[  5  15  40]
  [  4  15  60]]

 [[ 10  17  90]
  [  8  18 120]]]
18


## Reshape Array

In [101]:
C.reshape(3,6)

array([[ 0,  8, 10,  2,  6, 20],
       [ 5,  7, 30,  2,  9, 40],
       [ 5,  2, 50,  4,  3, 60]])

In [100]:
C.reshape(2, 3, 3)

array([[[ 0,  8, 10],
        [ 2,  6, 20],
        [ 5,  7, 30]],

       [[ 2,  9, 40],
        [ 5,  2, 50],
        [ 4,  3, 60]]])

In [102]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Place Holder

In [87]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [133]:
np.random.random([2,3])

array([[ 0.43515648,  0.76728998,  0.06092244],
       [ 0.16421167,  0.57816503,  0.25292271]])

In [138]:
np.ones([2,3], dtype=int)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [136]:
np.zeros([5,5])

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])